Repository openebs/api, pull requests merged in 2020-04, with the labels that each got.

#33 feat(apis): add new fields into BlockDevice api
  pkg/apis/openebs.io/v1alpha1/blockdevice_types.go
  pkg/internalapis/apis/openebs.io/blockdevice_types.go
  pkg/internalapis/apis/openebs.io/v1alpha1/zz_generated.conversion.go
Labels: ndm, needs-review

#34 feat(api): add label selector in BDC spec
  pkg/apis/openebs.io/v1alpha1/blockdeviceclaim_types.go
  pkg/apis/openebs.io/v1alpha1/zz_generated.deepcopy.go
  pkg/internalapis/apis/openebs.io/blockdeviceclaim_types.go
  pkg/internalapis/apis/openebs.io/v1alpha1/zz_generated.conversion.go
  pkg/internalapis/apis/openebs.io/zz_generated.deepcopy.go
Labels: ndm

#35 chore(cspc): update cspc api
  pkg/apis/cstor/v1/cstorpoolcluster.go
  pkg/internalapis/apis/cstor/cstorpoolcluster.go
  pkg/internalapis/apis/cstor/v1/zz_generated.conversion.go
Labels: cspc, needs-review

#38 chore(cspc): add builder functions for cspc
  pkg/apis/cstor/v1/cstorpoolclusterbuilder.go
  pkg/apis/cstor/v1/cstorpoolinstancebuilder.go
Labels: cspc, needs-review

#37 chore(cspi): add various conditions in CStorPoolInstance
  pkg/apis/cstor/v1/cstorpoolinstance.go
  pkg/internalapis/apis/cstor/cstorpool_topology.go
  pkg/internalapis/apis/cstor/cstorpoolinstance.go
  pkg/internalapis/apis/cstor/v1/zz_generated.conversion.go
Labels: cspi

#40 fix(CSPI): update type of Capacity field in CStorPoolInstanceBlockdevice
  design/cstor/v1/cstorpool.md
  pkg/apis/cstor/v1/cstorpoolcluster.go
  pkg/internalapis/apis/cstor/cstorpool_topology.go
  pkg/internalapis/apis/cstor/cstorpoolcluster.go
Labels: cspc, cspi, needs-review

#42 fix(SnapshotInfo): Remove Used field under CVRs SnapshotInfo
  design/cstor/v1/cstorvolume.md
  pkg/apis/cstor/v1/cstorvolumereplica.go
  pkg/internalapis/apis/cstor/cstorpool_topology.go
  pkg/internalapis/apis/cstor/cstorvolumereplica.go
  pkg/internalapis/apis/cstor/v1/zz_generated.conversion.go
Labels: needs-review
